# Generated by Django 5.2 on 2025-04-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_address',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
