steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/django-cloud-ecommerce', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/django-cloud-ecommerce']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'django-cloud-ecommerce'
    - '--image'
    - 'gcr.io/$PROJECT_ID/django-cloud-ecommerce'
    - '--region'
    - 'europe-west1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'PROJECT_ID=$PROJECT_ID'

# Images to be stored in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/django-cloud-ecommerce'