# Generated by Django 5.2 on 2025-05-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_wishlist_wishlistitem'),
        ('products', '0005_category_material_care'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product', 'color', 'size'), name='unique_cart_item'),
        ),
    ]
