# Generated by Django 5.2 on 2025-05-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_size_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='material_care',
            field=models.TextField(blank=True, null=True),
        ),
    ]
