# Generated by Django 5.2 on 2025-05-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_material_care'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='shirtigo_size_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
